version: 0.0
os: linux

files:
  - source: start_docker.sh
    destination: /opt

hooks:
  BeforeInstall:
    - location: remove_existing_file.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root
