version: 0.0
os: linux

files:
  - source: start_docker.sh
    destination: /opt

hooks:
  BeforeInstall:
    - timeout: 300
      runas: root
      # Remove the existing start_docker.sh if it exists before copying the new one
      script: |
        if [ -f /opt/start_docker.sh ]; then
          rm /opt/start_docker.sh
        fi

  AfterInstall:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root
