version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /opt/start_docker.sh
      timeout: 300
      runas: root
